require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ZoneEntriesController do

  # This should return the minimal set of attributes required to create a valid
  # ZoneEntry. As you add validations to ZoneEntry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ZoneEntriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all zone_entries as @zone_entries" do
      zone_entry = ZoneEntry.create! valid_attributes
      get :index, {}, valid_session
      assigns(:zone_entries).should eq([zone_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested zone_entry as @zone_entry" do
      zone_entry = ZoneEntry.create! valid_attributes
      get :show, {:id => zone_entry.to_param}, valid_session
      assigns(:zone_entry).should eq(zone_entry)
    end
  end

  describe "GET new" do
    it "assigns a new zone_entry as @zone_entry" do
      get :new, {}, valid_session
      assigns(:zone_entry).should be_a_new(ZoneEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested zone_entry as @zone_entry" do
      zone_entry = ZoneEntry.create! valid_attributes
      get :edit, {:id => zone_entry.to_param}, valid_session
      assigns(:zone_entry).should eq(zone_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ZoneEntry" do
        expect {
          post :create, {:zone_entry => valid_attributes}, valid_session
        }.to change(ZoneEntry, :count).by(1)
      end

      it "assigns a newly created zone_entry as @zone_entry" do
        post :create, {:zone_entry => valid_attributes}, valid_session
        assigns(:zone_entry).should be_a(ZoneEntry)
        assigns(:zone_entry).should be_persisted
      end

      it "redirects to the created zone_entry" do
        post :create, {:zone_entry => valid_attributes}, valid_session
        response.should redirect_to(ZoneEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved zone_entry as @zone_entry" do
        # Trigger the behavior that occurs when invalid params are submitted
        ZoneEntry.any_instance.stub(:save).and_return(false)
        post :create, {:zone_entry => {}}, valid_session
        assigns(:zone_entry).should be_a_new(ZoneEntry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ZoneEntry.any_instance.stub(:save).and_return(false)
        post :create, {:zone_entry => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested zone_entry" do
        zone_entry = ZoneEntry.create! valid_attributes
        # Assuming there are no other zone_entries in the database, this
        # specifies that the ZoneEntry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ZoneEntry.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => zone_entry.to_param, :zone_entry => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested zone_entry as @zone_entry" do
        zone_entry = ZoneEntry.create! valid_attributes
        put :update, {:id => zone_entry.to_param, :zone_entry => valid_attributes}, valid_session
        assigns(:zone_entry).should eq(zone_entry)
      end

      it "redirects to the zone_entry" do
        zone_entry = ZoneEntry.create! valid_attributes
        put :update, {:id => zone_entry.to_param, :zone_entry => valid_attributes}, valid_session
        response.should redirect_to(zone_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the zone_entry as @zone_entry" do
        zone_entry = ZoneEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ZoneEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => zone_entry.to_param, :zone_entry => {}}, valid_session
        assigns(:zone_entry).should eq(zone_entry)
      end

      it "re-renders the 'edit' template" do
        zone_entry = ZoneEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ZoneEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => zone_entry.to_param, :zone_entry => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested zone_entry" do
      zone_entry = ZoneEntry.create! valid_attributes
      expect {
        delete :destroy, {:id => zone_entry.to_param}, valid_session
      }.to change(ZoneEntry, :count).by(-1)
    end

    it "redirects to the zone_entries list" do
      zone_entry = ZoneEntry.create! valid_attributes
      delete :destroy, {:id => zone_entry.to_param}, valid_session
      response.should redirect_to(zone_entries_url)
    end
  end

end
